// ═══════════════════════════════════════════════════════════════
// 20 tareas reales de construcción — Edificio Rosario Centro
// ═══════════════════════════════════════════════════════════════

export const GANTT_MOCK_TASKS = [
  /* ── OBRA GRUESA ─────────────────────────────────── */
  {
    id: 't1', name: 'Demolición y excavación',
    gremio: 'Movimiento de suelos', group: 'Obra Gruesa',
    start: '2026-02-02', end: '2026-02-13',
    progress: 100, milestone: false, color: '#92400E',
    estado: 'completada',
    deps: [],
    notes: 'Excavación manual + retroexcavadora.',
    linkedBudgetId: null,
  },
  {
    id: 't2', name: 'Fundaciones (vigas de encadenado)',
    gremio: 'Hormigón armado', group: 'Obra Gruesa',
    start: '2026-02-16', end: '2026-03-06',
    progress: 100, milestone: false, color: '#92400E',
    estado: 'completada',
    deps: [{ taskId: 't1', type: 'FS', lag: 0 }],
    notes: 'H-21, acero ADN 420.',
    linkedBudgetId: null,
  },
  {
    id: 't3', name: 'Estructura planta baja',
    gremio: 'Hormigón armado', group: 'Obra Gruesa',
    start: '2026-03-09', end: '2026-03-27',
    progress: 100, milestone: false, color: '#92400E',
    estado: 'completada',
    deps: [{ taskId: 't2', type: 'FS', lag: 0 }],
    notes: 'Columnas + losa reticular.',
    linkedBudgetId: null,
  },
  {
    id: 't4', name: 'Estructura planta alta',
    gremio: 'Hormigón armado', group: 'Obra Gruesa',
    start: '2026-03-30', end: '2026-04-17',
    progress: 80, milestone: false, color: '#92400E',
    estado: 'en_progreso',
    deps: [{ taskId: 't3', type: 'FS', lag: 0 }],
    notes: '',
    linkedBudgetId: null,
  },
  {
    id: 't5', name: 'Cubierta y techo',
    gremio: 'Techista', group: 'Obra Gruesa',
    start: '2026-04-20', end: '2026-04-30',
    progress: 0, milestone: false, color: '#78350F',
    estado: 'pendiente',
    deps: [{ taskId: 't4', type: 'FS', lag: 0 }],
    notes: '',
    linkedBudgetId: null,
  },
  {
    id: 't6', name: 'Mampostería exterior e interior',
    gremio: 'Albañilería', group: 'Obra Gruesa',
    start: '2026-03-23', end: '2026-04-24',
    progress: 40, milestone: false, color: '#B45309',
    estado: 'en_progreso',
    deps: [{ taskId: 't3', type: 'SS', lag: 10 }],
    notes: 'Bloque cerámico + tabique 10.',
    linkedBudgetId: null,
  },

  /* ── INSTALACIONES ───────────────────────────────── */
  {
    id: 't7', name: 'Instalación sanitaria (agua/cloaca)',
    gremio: 'Sanitario', group: 'Instalaciones',
    start: '2026-03-16', end: '2026-04-10',
    progress: 60, milestone: false, color: '#1D4ED8',
    estado: 'en_progreso',
    deps: [{ taskId: 't3', type: 'SS', lag: 5 }],
    notes: 'PP-R agua fría/caliente, PVC cloaca.',
    linkedBudgetId: 'budget-sanitario',
  },
  {
    id: 't8', name: 'Instalación de gas',
    gremio: 'Gasista', group: 'Instalaciones',
    start: '2026-03-23', end: '2026-04-10',
    progress: 50, milestone: false, color: '#D97706',
    estado: 'en_progreso',
    deps: [{ taskId: 't3', type: 'SS', lag: 10 }],
    notes: 'Cañería de acero negra. NAG 200.',
    linkedBudgetId: null,
  },
  {
    id: 't9', name: 'Instalación eléctrica',
    gremio: 'Electricista', group: 'Instalaciones',
    start: '2026-03-23', end: '2026-04-17',
    progress: 45, milestone: false, color: '#CA8A04',
    estado: 'en_progreso',
    deps: [{ taskId: 't3', type: 'SS', lag: 10 }],
    notes: 'Cañero + conductor. Tablero TG.',
    linkedBudgetId: null,
  },
  {
    id: 't10', name: 'Instalación termomecánica (HVAC)',
    gremio: 'Termomecánica', group: 'Instalaciones',
    start: '2026-04-13', end: '2026-04-30',
    progress: 0, milestone: false, color: '#DC2626',
    estado: 'pendiente',
    deps: [{ taskId: 't9', type: 'FS', lag: 0 }],
    notes: 'Split inverter + ventilación mecánica.',
    linkedBudgetId: null,
  },
  {
    id: 't11', name: 'Instalación sanitaria exterior',
    gremio: 'Sanitario', group: 'Instalaciones',
    start: '2026-04-27', end: '2026-05-15',
    progress: 0, milestone: false, color: '#1D4ED8',
    estado: 'pendiente',
    deps: [{ taskId: 't7', type: 'FF', lag: 0 }],
    notes: 'Cámara séptica + conexión red.',
    linkedBudgetId: 'budget-sanitario',
  },

  /* ── TERMINACIONES ───────────────────────────────── */
  {
    id: 't12', name: 'Revoques internos',
    gremio: 'Albañilería', group: 'Terminaciones',
    start: '2026-04-27', end: '2026-05-22',
    progress: 0, milestone: false, color: '#B45309',
    estado: 'pendiente',
    deps: [{ taskId: 't6', type: 'FS', lag: 5 }],
    notes: 'Jaharro + enlucido.',
    linkedBudgetId: null,
  },
  {
    id: 't13', name: 'Cielorrasos Durlock',
    gremio: 'Durlock', group: 'Terminaciones',
    start: '2026-05-04', end: '2026-05-22',
    progress: 0, milestone: false, color: '#7C3AED',
    estado: 'pendiente',
    deps: [{ taskId: 't12', type: 'SS', lag: 0 }, { taskId: 't9', type: 'FS', lag: 5 }],
    notes: '',
    linkedBudgetId: null,
  },
  {
    id: 't14', name: 'Revestimientos baños y cocina',
    gremio: 'Albañilería', group: 'Terminaciones',
    start: '2026-05-11', end: '2026-05-29',
    progress: 0, milestone: false, color: '#0891B2',
    estado: 'pendiente',
    deps: [{ taskId: 't7', type: 'FS', lag: 10 }],
    notes: 'Porcelanato 60×60.',
    linkedBudgetId: null,
  },
  {
    id: 't15', name: 'Contrapiso y carpeta',
    gremio: 'Albañilería', group: 'Terminaciones',
    start: '2026-05-04', end: '2026-05-15',
    progress: 0, milestone: false, color: '#B45309',
    estado: 'pendiente',
    deps: [{ taskId: 't12', type: 'FS', lag: 0 }],
    notes: 'Hormigón pobre H-8 + carpeta niveladora.',
    linkedBudgetId: null,
  },
  {
    id: 't16', name: 'Pisos cerámicos / porcelanato',
    gremio: 'Pisos', group: 'Terminaciones',
    start: '2026-05-18', end: '2026-06-05',
    progress: 0, milestone: false, color: '#0D9488',
    estado: 'pendiente',
    deps: [{ taskId: 't15', type: 'FS', lag: 5 }],
    notes: '',
    linkedBudgetId: null,
  },
  {
    id: 't17', name: 'Carpinterías de aluminio',
    gremio: 'Carpintería', group: 'Terminaciones',
    start: '2026-05-04', end: '2026-05-22',
    progress: 0, milestone: false, color: '#475569',
    estado: 'pendiente',
    deps: [{ taskId: 't5', type: 'FS', lag: 0 }],
    notes: 'DVH 4-9-4. Línea pesada.',
    linkedBudgetId: null,
  },
  {
    id: 't18', name: 'Pintura interior',
    gremio: 'Pintura', group: 'Terminaciones',
    start: '2026-06-01', end: '2026-06-19',
    progress: 0, milestone: false, color: '#6D28D9',
    estado: 'pendiente',
    deps: [{ taskId: 't13', type: 'FS', lag: 5 }, { taskId: 't16', type: 'SS', lag: 0 }],
    notes: 'Látex interior 2 manos.',
    linkedBudgetId: null,
  },

  /* ── EXTERIOR ────────────────────────────────────── */
  {
    id: 't19', name: 'Pintura exterior y enduído',
    gremio: 'Pintura', group: 'Exterior',
    start: '2026-05-18', end: '2026-06-05',
    progress: 0, milestone: false, color: '#6D28D9',
    estado: 'pendiente',
    deps: [{ taskId: 't5', type: 'FS', lag: 10 }],
    notes: 'Revestimiento texturado exterior.',
    linkedBudgetId: null,
  },
  {
    id: 't20', name: 'Limpieza final y entrega',
    gremio: 'Varios', group: 'Exterior',
    start: '2026-06-22', end: '2026-06-26',
    progress: 0, milestone: true, color: '#A8102E',
    estado: 'pendiente',
    deps: [
      { taskId: 't18', type: 'FS', lag: 0 },
      { taskId: 't19', type: 'FS', lag: 5 },
      { taskId: 't11', type: 'FS', lag: 5 },
    ],
    notes: 'Hito de entrega final de obra.',
    linkedBudgetId: null,
  },
];
